package engine

// The bidding systems of cli/systems/index.json, for the tests that hold for
// any system: the Python reference (expansion, conformance cases, whole
// auctions), the legality of the calls, the par bench and the PDF run once per
// system. A system is a folder, cli/systems/<id>/ (rules.yaml, rules.pdf,
// rules.en.pdf, pbn/), and its reference data another, testdata/systems/<id>/
// (rules.json, tests.json, golden.json, par_baseline.json), all of it
// generated by tools/python_tools/regen_system.py.
//
// The other tests of the package describe the SEF itself (a given hand opens
// 1NT...) and keep bidding with cli/systems/sef/rules.yaml only.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"testing"
)

const (
	systemsDir    = "../cli/systems"
	systemsData   = "testdata/systems"
	defaultSystem = "sef"
)

// systemID is what the page accepts as a system identifier (bids-wasm.js).
var systemID = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]*$`)

type testSystem struct {
	ID    string // folder name under cli/systems: the subtest name
	Rules *RuleSet
}

// file is a file of the system's folder: rules.yaml, rules.pdf...
func (s *testSystem) file(name string) string { return filepath.Join(systemsDir, s.ID, name) }

// data is one of the system's reference files: rules.json, tests.json...
func (s *testSystem) data(name string) string { return filepath.Join(systemsData, s.ID, name) }

// regenerateCmd is what rebuilds every reference file of the system.
func (s *testSystem) regenerateCmd() string {
	return "./update-system.sh " + s.ID + " (ou .\\update-system.ps1 " + s.ID + ")"
}

// loadSystems reads index.json and loads each system it declares: a folder
// that is missing, or rules the engine refuses, fail here, before any page
// offers them.
func loadSystems(t *testing.T) []*testSystem {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(systemsDir, "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	var index struct {
		Systems []struct {
			ID string `json:"id"`
		} `json:"systems"`
	}
	if err := json.Unmarshal(data, &index); err != nil {
		t.Fatal(err)
	}
	var out []*testSystem
	hasDefault := false
	for _, e := range index.Systems {
		hasDefault = hasDefault || e.ID == defaultSystem
		if !systemID.MatchString(e.ID) {
			t.Fatalf("index.json : identifiant de système invalide %q", e.ID)
		}
		s := &testSystem{ID: e.ID}
		yaml, err := os.ReadFile(s.file("rules.yaml"))
		if err != nil {
			t.Fatal(err)
		}
		if s.Rules, err = LoadRules(yaml); err != nil {
			t.Fatalf("%s : %v", e.ID, err)
		}
		out = append(out, s)
	}
	if !hasDefault {
		t.Fatalf("index.json doit déclarer %q : c'est le système par défaut de la page", defaultSystem)
	}
	return out
}

// TestThemeDealsAreComplete parses every deal of every thematic series of the
// systems (cli/systems/<id>/pbn/*.pbn): each one must be a complete deal, four
// 13-card hands without a duplicated card. ParsePBNBoards is what the page's
// data goes through, so a truncated or mistyped [Deal] tag fails here instead
// of reaching the players.
func TestThemeDealsAreComplete(t *testing.T) {
	files, err := filepath.Glob(filepath.Join(systemsDir, "*", "pbn", "*.pbn"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatalf("aucune série de donnes sous %s", filepath.Join(systemsDir, "*", "pbn"))
	}
	for _, path := range files {
		name := filepath.ToSlash(path)
		t.Run(name, func(t *testing.T) {
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			deals, err := ParsePBNBoards(data)
			if err != nil {
				t.Fatalf("%s : %v", name, err)
			}
			if len(deals) == 0 {
				t.Fatalf("%s : aucune donne", name)
			}
		})
	}
}

// TestThemeIndexDealCounts: each entry of a thematic index
// (cli/systems/<id>/pbn/index.json) carries "deals", the number of deals of
// its file that hold their auction — the ones training can play. The page
// shows their sum on the Practise card without reading the files, so a theme
// added or changed without updating its count fails here.
func TestThemeIndexDealCounts(t *testing.T) {
	indexes, err := filepath.Glob(filepath.Join(systemsDir, "*", "pbn", "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	auctionTag := regexp.MustCompile(`\[Auction\s`)
	for _, idx := range indexes {
		data, err := os.ReadFile(idx)
		if err != nil {
			t.Fatal(err)
		}
		var body struct {
			Files []struct {
				File  string `json:"file"`
				Deals *int   `json:"deals"`
			} `json:"files"`
		}
		if err := json.Unmarshal(data, &body); err != nil {
			t.Fatalf("%s : %v", idx, err)
		}
		for _, f := range body.Files {
			text, err := os.ReadFile(filepath.Join(filepath.Dir(idx), f.File))
			if err != nil {
				t.Errorf("%s : %v", idx, err)
				continue
			}
			want := len(auctionTag.FindAll(text, -1))
			if f.Deals == nil || *f.Deals != want {
				got := "absent"
				if f.Deals != nil {
					got = strconv.Itoa(*f.Deals)
				}
				t.Errorf("%s : %s : \"deals\" vaut %s, le fichier a %d donnes avec enchère", idx, f.File, got, want)
			}
		}
	}
}

// forEachSystem runs fn as a subtest per system (go test -run 'Test…/id'
// picks one), with that system's rules installed; the SEF is put back
// afterwards for the tests that follow.
func forEachSystem(t *testing.T, fn func(t *testing.T, s *testSystem)) {
	t.Helper()
	def := loadTestRules(t)
	defer SetRules(def)
	for _, s := range loadSystems(t) {
		t.Run(s.ID, func(t *testing.T) {
			SetRules(s.Rules)
			fn(t, s)
		})
	}
}
