package engine

// The bidding systems of cli/rules/index.json, for the tests that hold for any
// system: the Python reference (expansion, conformance cases, whole auctions),
// the legality of the calls and the par bench run once per system, each
// against its own data. default.yaml keeps the historical file names; another
// system, mon-systeme.yaml, adds its stem: sef_tests.mon-systeme.json,
// testdata/golden_python.mon-systeme.json, and so on. All of them are
// generated by tools/python_tools/regen_system.py.
//
// The other tests of the package describe the SEF itself (a given hand opens
// 1NT...) and keep bidding with default.yaml only.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const rulesDir = "../cli/rules"

type testSystem struct {
	File  string // file name in cli/rules, as index.json gives it
	Stem  string // File without its extension: the subtest name
	Rules *RuleSet
}

// dataFile inserts the system's stem before the extension of a reference
// file, except for default.yaml, whose files predate the other systems.
func (s *testSystem) dataFile(path string) string {
	if s.Stem == "default" {
		return path
	}
	ext := filepath.Ext(path)
	return strings.TrimSuffix(path, ext) + "." + s.Stem + ext
}

func (s *testSystem) pyRulesJSON() string  { return s.dataFile(pyRulesJSON) }
func (s *testSystem) pyTestsJSON() string  { return s.dataFile(pyTestsJSON) }
func (s *testSystem) goldenPython() string { return s.dataFile(goldenPython) }
func (s *testSystem) parBaseline() string  { return s.dataFile(parBenchBaseline) }

// regenerateCmd is what rebuilds every reference file of the system.
func (s *testSystem) regenerateCmd() string {
	return "cd tools/python_tools && python regen_system.py ../../cli/rules/" + s.File
}

// loadSystems reads index.json and loads each system it declares: a file
// that is missing or that the engine refuses fails here, before any page
// offers it.
func loadSystems(t *testing.T) []*testSystem {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(rulesDir, "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	var index struct {
		Systems []struct {
			File string `json:"file"`
		} `json:"systems"`
	}
	if err := json.Unmarshal(data, &index); err != nil {
		t.Fatal(err)
	}
	var out []*testSystem
	for _, e := range index.Systems {
		s := &testSystem{File: e.File, Stem: strings.TrimSuffix(e.File, filepath.Ext(e.File))}
		yaml, err := os.ReadFile(filepath.Join(rulesDir, e.File))
		if err != nil {
			t.Fatal(err)
		}
		if s.Rules, err = LoadRules(yaml); err != nil {
			t.Fatalf("%s : %v", e.File, err)
		}
		out = append(out, s)
	}
	if len(out) == 0 {
		t.Fatal("index.json ne déclare aucun système")
	}
	return out
}

// forEachSystem runs fn as a subtest per system (go test -run 'Test…/stem'
// picks one), with that system's rules installed; default.yaml is put back
// afterwards for the tests that follow.
func forEachSystem(t *testing.T, fn func(t *testing.T, s *testSystem)) {
	t.Helper()
	def := loadTestRules(t)
	defer SetRules(def)
	for _, s := range loadSystems(t) {
		t.Run(s.Stem, func(t *testing.T) {
			SetRules(s.Rules)
			fn(t, s)
		})
	}
}
